config/routes.rb
Rails.application.routes.draw do
  resources :imgposts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imgpost.rb
class Imgpost < ApplicationRecord
  mount_uploader :image, AttachmentUploader
  # Tells rails to use this uploader for this model.
  validates :title, presence: true
  # Make sure the title is present.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imgposts_controller.rb
class ImgpostsController < ApplicationController
  before_action :set_imgpost, only: [:show, :edit, :update, :destroy]

  # GET /imgposts
  # GET /imgposts.json
  def index
    @imgposts = Imgpost.all
  end

  # GET /imgposts/1
  # GET /imgposts/1.json
  def show
  end

  # GET /imgposts/new
  def new
    @imgpost = Imgpost.new
  end

  # GET /imgposts/1/edit
  def edit
  end

  # POST /imgposts
  # POST /imgposts.json
  def create
    @imgpost = Imgpost.new(imgpost_params)

    respond_to do |format|
      if @imgpost.save
        format.html { redirect_to @imgpost, notice: 'Imgpost was successfully created.' }
        format.json { render :show, status: :created, location: @imgpost }
      else
        format.html { render :new }
        format.json { render json: @imgpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imgposts/1
  # PATCH/PUT /imgposts/1.json
  def update
    respond_to do |format|
      if @imgpost.update(imgpost_params)
        format.html { redirect_to @imgpost, notice: 'Imgpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @imgpost }
      else
        format.html { render :edit }
        format.json { render json: @imgpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imgposts/1
  # DELETE /imgposts/1.json
  def destroy
    @imgpost.destroy
    respond_to do |format|
      format.html { redirect_to imgposts_url, notice: 'Imgpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imgpost
      @imgpost = Imgpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imgpost_params
      params.require(:imgpost).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imgposts_helper.rb
module ImgpostsHelper
end

app/views/imgposts/_form.html.erb
<%= form_with(model: imgpost, local: true) do |form| %>
  <% if imgpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imgpost.errors.count, "error") %> prohibited this imgpost from being saved:</h2>

      <ul>
      <% imgpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imgposts/edit.html.erb
<h1>Editing Imgpost</h1>

<%= render 'form', imgpost: @imgpost %>

<%= link_to 'Show', @imgpost %> |
<%= link_to 'Back', imgposts_path %>

app/views/imgposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imgposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imgposts.each do |imgpost| %>
      <tr>
        <td><%= imgpost.title %></td>
        <td><%= imgpost.content %></td>
        <td><%= image_tag("#{imgpost.image}") %></td>
        <td><%= link_to 'Show', imgpost %></td>
        <td><%= link_to 'Edit', edit_imgpost_path(imgpost) %></td>
        <td><%= link_to 'Destroy', imgpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imgpost', new_imgpost_path %>

app/views/imgposts/new.html.erb
<h1>New Imgpost</h1>

<%= render 'form', imgpost: @imgpost %>

<%= link_to 'Back', imgposts_path %>

app/views/imgposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @imgpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @imgpost.content %>
</p>

<p>
    <strong>사진:</strong>
    <%= image_tag("#{@imgpost.image}", class: "show_img") %>
</p>

<%= link_to 'Edit', edit_imgpost_path(@imgpost) %> |
<%= link_to 'Back', imgposts_path %>

<style>
  .show_img {
    transform: rotate(180deg);
    height: 300px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgUpload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>